# Generated by Django 5.2.16 on 2026-07-21 21:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('concept', models.TextField(blank=True, help_text='Concetto del personaggio')),
                ('promise_marks', models.IntegerField(default=0)),
                ('quintessence_1', models.CharField(blank=True, max_length=100)),
                ('quintessence_2', models.CharField(blank=True, max_length=100)),
                ('quintessence_3', models.CharField(blank=True, max_length=100)),
                ('quintessence_4', models.CharField(blank=True, max_length=100)),
                ('backpack', models.JSONField(blank=True, default=list)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('fellowship_theme_notes', models.JSONField(blank=True, default=list)),
                ('quest_notes', models.JSONField(blank=True, default=list)),
                ('abandon_milestone_marks', models.IntegerField(default=0)),
                ('improve_milestone_marks', models.IntegerField(default=0)),
                ('special_improvements', models.JSONField(blank=True, default=list)),
                ('history', models.TextField(blank=True)),
                ('portrait_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='campaigns.campaign')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='users.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FellowshipRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companion_name', models.CharField(max_length=100)),
                ('relationship_tag', models.CharField(max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fellowship_relations', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='ThemeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=50)),
                ('type_name', models.CharField(blank=True, max_length=100)),
                ('notes_main', models.JSONField(blank=True, default=list)),
                ('notes_secondary', models.JSONField(blank=True, default=list)),
                ('quest_notes', models.JSONField(blank=True, default=list)),
                ('abandon_marks', models.IntegerField(default=0)),
                ('improve_marks', models.IntegerField(default=0)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_cards', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='characters.character')),
            ],
            options={
                'unique_together': {('character', 'number')},
            },
        ),
    ]
