# Generated by Django 5.2.16 on 2026-07-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themecard',
            name='card_type',
            field=models.CharField(choices=[('CIRCUMSTANCE', 'Circumstance'), ('COMPANION', 'Companion'), ('DEVOTION', 'Devotion'), ('DUTY', 'Duty'), ('KNOWLEDGE', 'Knowledge'), ('MAGIC', 'Magic'), ('MONSTROSITY', 'Monstrosity'), ('PAST', 'Past'), ('PEOPLE', 'People'), ('PERSONALITY', 'Personality'), ('POSSESSIONS', 'Possessions'), ('PRODIGIOUS_ABILITY', 'Prodigious Ability'), ('RELIC', 'Relic'), ('SKILL_OR_TRADE', 'Skill or Trade'), ('TRAIT', 'Trait'), ('UNCANNY_BEING', 'Uncanny Being')], default='CIRCUMSTANCE', max_length=20),
        ),
        migrations.AlterField(
            model_name='themecard',
            name='type_name',
            field=models.CharField(blank=True, help_text="Es: 'La Spada del Nonno' o 'Occhio Notturno'", max_length=100),
        ),
    ]
