# Generated by Django 5.2.16 on 2026-07-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_max_players_campaign_status'),
        ('characters', '0002_alter_themecard_card_type_alter_themecard_type_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='fellowship_theme_notes',
            new_name='fellowship_special_improvements',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='quintessence_1',
            new_name='fellowship_theme_title',
        ),
        migrations.RemoveField(
            model_name='character',
            name='abandon_milestone_marks',
        ),
        migrations.RemoveField(
            model_name='character',
            name='improve_milestone_marks',
        ),
        migrations.RemoveField(
            model_name='character',
            name='quest_notes',
        ),
        migrations.RemoveField(
            model_name='character',
            name='quintessence_2',
        ),
        migrations.RemoveField(
            model_name='character',
            name='quintessence_3',
        ),
        migrations.RemoveField(
            model_name='character',
            name='quintessence_4',
        ),
        migrations.RemoveField(
            model_name='character',
            name='special_improvements',
        ),
        migrations.RemoveField(
            model_name='themecard',
            name='abandon_marks',
        ),
        migrations.RemoveField(
            model_name='themecard',
            name='improve_marks',
        ),
        migrations.RemoveField(
            model_name='themecard',
            name='notes_main',
        ),
        migrations.RemoveField(
            model_name='themecard',
            name='notes_secondary',
        ),
        migrations.RemoveField(
            model_name='themecard',
            name='quest_notes',
        ),
        migrations.AddField(
            model_name='character',
            name='fellowship_quest',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='fellowship_rags_lines',
            field=models.JSONField(blank=True, default=list, help_text="[{'text': '', 'type': 'slash'}]"),
        ),
        migrations.AddField(
            model_name='character',
            name='fellowship_theme_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='fellowship_tracks',
            field=models.JSONField(blank=True, default=dict, help_text="{'abandon': 0, 'improve': 0, 'milestone': 0}"),
        ),
        migrations.AddField(
            model_name='character',
            name='promise',
            field=models.TextField(blank=True, help_text='La promessa del personaggio'),
        ),
        migrations.AddField(
            model_name='character',
            name='quintessence',
            field=models.IntegerField(default=0, help_text='Da 0 a 5'),
        ),
        migrations.AddField(
            model_name='themecard',
            name='description',
            field=models.TextField(blank=True, help_text='Descrizione positiva o negativa'),
        ),
        migrations.AddField(
            model_name='themecard',
            name='quest',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='themecard',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positivo'), ('negative', 'Negativo'), ('neutral', 'Neutro')], default='neutral', max_length=10),
        ),
        migrations.AddField(
            model_name='themecard',
            name='special_improvements',
            field=models.JSONField(blank=True, default=list, help_text='Lista di miglioramenti speciali'),
        ),
        migrations.AddField(
            model_name='themecard',
            name='tracks',
            field=models.JSONField(blank=True, default=dict, help_text="{'abandon': 0, 'improve': 0}"),
        ),
        migrations.AlterField(
            model_name='character',
            name='backpack',
            field=models.JSONField(blank=True, default=list, help_text='Lista di oggetti: [{name, qty}]'),
        ),
        migrations.AlterField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='promise_marks',
            field=models.IntegerField(default=0, help_text='Da 0 a 5'),
        ),
        migrations.AlterField(
            model_name='themecard',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_cards', to='characters.character'),
        ),
        migrations.AlterField(
            model_name='themecard',
            name='type_name',
            field=models.CharField(blank=True, help_text='Titolo specifico del tema', max_length=100),
        ),
    ]
