# Generated by Django 5.2.16 on 2026-07-21 21:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0002_alter_themecard_card_type_alter_themecard_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiceRoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dice_type', models.CharField(default='d6', max_length=10)),
                ('num_dice', models.IntegerField(default=1)),
                ('modifier', models.IntegerField(default=0)),
                ('raw_results', models.JSONField(default=list)),
                ('total', models.IntegerField()),
                ('success_level', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('tags_applied', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice_rolls', to='characters.character')),
            ],
        ),
    ]
