# Generated by Django 5.2.16 on 2026-07-21 20:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('storyteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to='users.storytellerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('player', 'Giocatore'), ('observer', 'Osservatore')], default='player', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='campaigns.campaign')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to='users.playerprofile')),
            ],
            options={
                'unique_together': {('campaign', 'player')},
            },
        ),
    ]
