# Generated by Django 5.2.16 on 2026-07-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='max_players',
            field=models.IntegerField(default=5, help_text='Numero minimo di giocatori per poter partire'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('RECRUITING', 'In Reclutamento'), ('STARTED', 'Aavviata'), ('PAUSED', 'In Pausa'), ('CONCLUDED', 'Conclusa')], default='RECRUITING', max_length=20),
        ),
    ]
